version: '3'
services:
  minio_php:
    container_name: minio-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html

  minio_nginx:
    container_name: minio-nginx
    hostname: nginx
    image: nginx:1.19
    restart: unless-stopped
    depends_on:
      - minio_php
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - ./docker/virtualhost.conf:/etc/nginx/conf.d/default.conf

  minio_db:
    container_name: minio-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: minio
      POSTGRES_USER: minio-user
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
    volumes:
      - dbminio:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  minio_storage:
    container_name: minio-storage
    image: minio/minio
    ports: 
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=12345678
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  dbminio:
  minio-data:
